//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GanafWeb.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int postId { get; set; }
        public string comment1 { get; set; }
        public System.DateTime commentDate { get; set; }
    
        public virtual post post { get; set; }
        public virtual user user { get; set; }
    }
}
