//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GanafWeb.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int id { get; set; }
        public string postedBy { get; set; }
        public System.DateTime postDate { get; set; }
        public string body { get; set; }
        public string topic { get; set; }
        public string intro { get; set; }
        public string image { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
